/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_tunes.dbobj.tables;


import com.github.curiousoddman.curious_tunes.dbobj.Indexes;
import com.github.curiousoddman.curious_tunes.dbobj.Keys;
import com.github.curiousoddman.curious_tunes.dbobj.Public;
import com.github.curiousoddman.curious_tunes.dbobj.tables.records.AlbumRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Album extends TableImpl<AlbumRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.ALBUM</code>
     */
    public static final Album ALBUM = new Album();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AlbumRecord> getRecordType() {
        return AlbumRecord.class;
    }

    /**
     * The column <code>public.ALBUM.ID</code>.
     */
    public final TableField<AlbumRecord, Integer> ID = createField(DSL.name("ID"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.ALBUM.FK_ARTIST</code>.
     */
    public final TableField<AlbumRecord, Integer> FK_ARTIST = createField(DSL.name("FK_ARTIST"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.ALBUM.NAME</code>.
     */
    public final TableField<AlbumRecord, String> NAME = createField(DSL.name("NAME"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.ALBUM.IMAGE</code>.
     */
    public final TableField<AlbumRecord, byte[]> IMAGE = createField(DSL.name("IMAGE"), SQLDataType.VARBINARY, this, "");

    /**
     * The column <code>public.ALBUM.IMAGE_TYPE</code>.
     */
    public final TableField<AlbumRecord, Byte> IMAGE_TYPE = createField(DSL.name("IMAGE_TYPE"), SQLDataType.TINYINT, this, "");

    private Album(Name alias, Table<AlbumRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Album(Name alias, Table<AlbumRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.ALBUM</code> table reference
     */
    public Album(String alias) {
        this(DSL.name(alias), ALBUM);
    }

    /**
     * Create an aliased <code>public.ALBUM</code> table reference
     */
    public Album(Name alias) {
        this(alias, ALBUM);
    }

    /**
     * Create a <code>public.ALBUM</code> table reference
     */
    public Album() {
        this(DSL.name("ALBUM"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.ALBUM_ARTIST_INDEX, Indexes.ALBUM_NAME_INDEX);
    }

    @Override
    public Identity<AlbumRecord, Integer> getIdentity() {
        return (Identity<AlbumRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<AlbumRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_3;
    }

    @Override
    public Album as(String alias) {
        return new Album(DSL.name(alias), this);
    }

    @Override
    public Album as(Name alias) {
        return new Album(alias, this);
    }

    @Override
    public Album as(Table<?> alias) {
        return new Album(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Album rename(String name) {
        return new Album(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Album rename(Name name) {
        return new Album(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Album rename(Table<?> name) {
        return new Album(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Album where(Condition condition) {
        return new Album(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Album where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Album where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Album where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Album where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Album where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Album where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Album where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Album whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Album whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
