/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_tunes.dbobj.tables;


import com.github.curiousoddman.curious_tunes.dbobj.Indexes;
import com.github.curiousoddman.curious_tunes.dbobj.Keys;
import com.github.curiousoddman.curious_tunes.dbobj.Public;
import com.github.curiousoddman.curious_tunes.dbobj.tables.records.ArtistRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.20.10",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Artist extends TableImpl<ArtistRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.ARTIST</code>
     */
    public static final Artist ARTIST = new Artist();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ArtistRecord> getRecordType() {
        return ArtistRecord.class;
    }

    /**
     * The column <code>public.ARTIST.ID</code>.
     */
    public final TableField<ArtistRecord, Integer> ID = createField(DSL.name("ID"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.ARTIST.NAME</code>.
     */
    public final TableField<ArtistRecord, String> NAME = createField(DSL.name("NAME"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.ARTIST.ICON</code>.
     */
    public final TableField<ArtistRecord, byte[]> ICON = createField(DSL.name("ICON"), SQLDataType.VARBINARY, this, "");

    private Artist(Name alias, Table<ArtistRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Artist(Name alias, Table<ArtistRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.ARTIST</code> table reference
     */
    public Artist(String alias) {
        this(DSL.name(alias), ARTIST);
    }

    /**
     * Create an aliased <code>public.ARTIST</code> table reference
     */
    public Artist(Name alias) {
        this(alias, ARTIST);
    }

    /**
     * Create a <code>public.ARTIST</code> table reference
     */
    public Artist() {
        this(DSL.name("ARTIST"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.ARTIST_NAME_INDEX);
    }

    @Override
    public Identity<ArtistRecord, Integer> getIdentity() {
        return (Identity<ArtistRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ArtistRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_7;
    }

    @Override
    public Artist as(String alias) {
        return new Artist(DSL.name(alias), this);
    }

    @Override
    public Artist as(Name alias) {
        return new Artist(alias, this);
    }

    @Override
    public Artist as(Table<?> alias) {
        return new Artist(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Artist rename(String name) {
        return new Artist(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Artist rename(Name name) {
        return new Artist(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Artist rename(Table<?> name) {
        return new Artist(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Artist where(Condition condition) {
        return new Artist(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Artist where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Artist where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Artist where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Artist where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Artist where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Artist where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Artist where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Artist whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Artist whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
