/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_tunes.dbobj.tables;


import com.github.curiousoddman.curious_tunes.dbobj.Indexes;
import com.github.curiousoddman.curious_tunes.dbobj.Keys;
import com.github.curiousoddman.curious_tunes.dbobj.Public;
import com.github.curiousoddman.curious_tunes.dbobj.tables.records.PlaybackHistoryRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PlaybackHistory extends TableImpl<PlaybackHistoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.PLAYBACK_HISTORY</code>
     */
    public static final PlaybackHistory PLAYBACK_HISTORY = new PlaybackHistory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PlaybackHistoryRecord> getRecordType() {
        return PlaybackHistoryRecord.class;
    }

    /**
     * The column <code>public.PLAYBACK_HISTORY.ID</code>.
     */
    public final TableField<PlaybackHistoryRecord, Integer> ID = createField(DSL.name("ID"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.PLAYBACK_HISTORY.DATETIME</code>.
     */
    public final TableField<PlaybackHistoryRecord, OffsetDateTime> DATETIME = createField(DSL.name("DATETIME"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.PLAYBACK_HISTORY.FK_TRACK</code>.
     */
    public final TableField<PlaybackHistoryRecord, Integer> FK_TRACK = createField(DSL.name("FK_TRACK"), SQLDataType.INTEGER, this, "");

    private PlaybackHistory(Name alias, Table<PlaybackHistoryRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PlaybackHistory(Name alias, Table<PlaybackHistoryRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.PLAYBACK_HISTORY</code> table reference
     */
    public PlaybackHistory(String alias) {
        this(DSL.name(alias), PLAYBACK_HISTORY);
    }

    /**
     * Create an aliased <code>public.PLAYBACK_HISTORY</code> table reference
     */
    public PlaybackHistory(Name alias) {
        this(alias, PLAYBACK_HISTORY);
    }

    /**
     * Create a <code>public.PLAYBACK_HISTORY</code> table reference
     */
    public PlaybackHistory() {
        this(DSL.name("PLAYBACK_HISTORY"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.PLAYBACK_HISTORY_TRACK_INDEX);
    }

    @Override
    public Identity<PlaybackHistoryRecord, Integer> getIdentity() {
        return (Identity<PlaybackHistoryRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<PlaybackHistoryRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_8;
    }

    @Override
    public PlaybackHistory as(String alias) {
        return new PlaybackHistory(DSL.name(alias), this);
    }

    @Override
    public PlaybackHistory as(Name alias) {
        return new PlaybackHistory(alias, this);
    }

    @Override
    public PlaybackHistory as(Table<?> alias) {
        return new PlaybackHistory(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PlaybackHistory rename(String name) {
        return new PlaybackHistory(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PlaybackHistory rename(Name name) {
        return new PlaybackHistory(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PlaybackHistory rename(Table<?> name) {
        return new PlaybackHistory(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlaybackHistory where(Condition condition) {
        return new PlaybackHistory(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlaybackHistory where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlaybackHistory where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlaybackHistory where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PlaybackHistory where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PlaybackHistory where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PlaybackHistory where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PlaybackHistory where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlaybackHistory whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlaybackHistory whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
