/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_tunes.dbobj.tables;


import com.github.curiousoddman.curious_tunes.dbobj.Indexes;
import com.github.curiousoddman.curious_tunes.dbobj.Keys;
import com.github.curiousoddman.curious_tunes.dbobj.Public;
import com.github.curiousoddman.curious_tunes.dbobj.tables.records.TrackRecord;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Track extends TableImpl<TrackRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.TRACK</code>
     */
    public static final Track TRACK = new Track();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TrackRecord> getRecordType() {
        return TrackRecord.class;
    }

    /**
     * The column <code>public.TRACK.ID</code>.
     */
    public final TableField<TrackRecord, Integer> ID = createField(DSL.name("ID"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.TRACK.FK_ALBUM</code>.
     */
    public final TableField<TrackRecord, Integer> FK_ALBUM = createField(DSL.name("FK_ALBUM"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.TRACK.TITLE</code>.
     */
    public final TableField<TrackRecord, String> TITLE = createField(DSL.name("TITLE"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.TRACK.TRACK_NUMBER</code>.
     */
    public final TableField<TrackRecord, Integer> TRACK_NUMBER = createField(DSL.name("TRACK_NUMBER"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.TRACK.RELEASE_DATE</code>.
     */
    public final TableField<TrackRecord, String> RELEASE_DATE = createField(DSL.name("RELEASE_DATE"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.TRACK.DISK_NUMBER</code>.
     */
    public final TableField<TrackRecord, Integer> DISK_NUMBER = createField(DSL.name("DISK_NUMBER"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.TRACK.CREATOR</code>.
     */
    public final TableField<TrackRecord, String> CREATOR = createField(DSL.name("CREATOR"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.TRACK.AUDIO_SAMPLE_RATE</code>.
     */
    public final TableField<TrackRecord, Integer> AUDIO_SAMPLE_RATE = createField(DSL.name("AUDIO_SAMPLE_RATE"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.TRACK.GENRE</code>.
     */
    public final TableField<TrackRecord, String> GENRE = createField(DSL.name("GENRE"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.TRACK.COMPOSER</code>.
     */
    public final TableField<TrackRecord, String> COMPOSER = createField(DSL.name("COMPOSER"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.TRACK.FILE_LOCATION</code>.
     */
    public final TableField<TrackRecord, String> FILE_LOCATION = createField(DSL.name("FILE_LOCATION"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.TRACK.DURATION_SECONDS</code>.
     */
    public final TableField<TrackRecord, BigDecimal> DURATION_SECONDS = createField(DSL.name("DURATION_SECONDS"), SQLDataType.DECIMAL(20, 14), this, "");

    /**
     * The column <code>public.TRACK.STATUS</code>.
     */
    public final TableField<TrackRecord, String> STATUS = createField(DSL.name("STATUS"), SQLDataType.VARCHAR, this, "");

    private Track(Name alias, Table<TrackRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Track(Name alias, Table<TrackRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.TRACK</code> table reference
     */
    public Track(String alias) {
        this(DSL.name(alias), TRACK);
    }

    /**
     * Create an aliased <code>public.TRACK</code> table reference
     */
    public Track(Name alias) {
        this(alias, TRACK);
    }

    /**
     * Create a <code>public.TRACK</code> table reference
     */
    public Track() {
        this(DSL.name("TRACK"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.TRACK_ALBUM_INDEX, Indexes.TRACK_TITLE_INDEX);
    }

    @Override
    public Identity<TrackRecord, Integer> getIdentity() {
        return (Identity<TrackRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<TrackRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_4;
    }

    @Override
    public Track as(String alias) {
        return new Track(DSL.name(alias), this);
    }

    @Override
    public Track as(Name alias) {
        return new Track(alias, this);
    }

    @Override
    public Track as(Table<?> alias) {
        return new Track(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Track rename(String name) {
        return new Track(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Track rename(Name name) {
        return new Track(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Track rename(Table<?> name) {
        return new Track(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Track where(Condition condition) {
        return new Track(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Track where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Track where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Track where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Track where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Track where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Track where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Track where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Track whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Track whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
