/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_tunes.dbobj;


import com.github.curiousoddman.curious_tunes.dbobj.tables.Album;
import com.github.curiousoddman.curious_tunes.dbobj.tables.Artist;
import com.github.curiousoddman.curious_tunes.dbobj.tables.FlywaySchemaHistory;
import com.github.curiousoddman.curious_tunes.dbobj.tables.PlaybackHistory;
import com.github.curiousoddman.curious_tunes.dbobj.tables.Track;
import com.github.curiousoddman.curious_tunes.dbobj.tables.records.AlbumRecord;
import com.github.curiousoddman.curious_tunes.dbobj.tables.records.ArtistRecord;
import com.github.curiousoddman.curious_tunes.dbobj.tables.records.FlywaySchemaHistoryRecord;
import com.github.curiousoddman.curious_tunes.dbobj.tables.records.PlaybackHistoryRecord;
import com.github.curiousoddman.curious_tunes.dbobj.tables.records.TrackRecord;

import javax.annotation.processing.Generated;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AlbumRecord> CONSTRAINT_3 = Internal.createUniqueKey(Album.ALBUM, DSL.name("CONSTRAINT_3"), new TableField[] { Album.ALBUM.ID }, true);
    public static final UniqueKey<ArtistRecord> CONSTRAINT_7 = Internal.createUniqueKey(Artist.ARTIST, DSL.name("CONSTRAINT_7"), new TableField[] { Artist.ARTIST.ID }, true);
    public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, DSL.name("flyway_schema_history_pk"), new TableField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
    public static final UniqueKey<PlaybackHistoryRecord> CONSTRAINT_8 = Internal.createUniqueKey(PlaybackHistory.PLAYBACK_HISTORY, DSL.name("CONSTRAINT_8"), new TableField[] { PlaybackHistory.PLAYBACK_HISTORY.ID }, true);
    public static final UniqueKey<TrackRecord> CONSTRAINT_4 = Internal.createUniqueKey(Track.TRACK, DSL.name("CONSTRAINT_4"), new TableField[] { Track.TRACK.ID }, true);
}
