/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_tunes.dbobj;


import com.github.curiousoddman.curious_tunes.dbobj.tables.Album;
import com.github.curiousoddman.curious_tunes.dbobj.tables.Artist;
import com.github.curiousoddman.curious_tunes.dbobj.tables.FlywaySchemaHistory;
import com.github.curiousoddman.curious_tunes.dbobj.tables.PendingActions;
import com.github.curiousoddman.curious_tunes.dbobj.tables.PlaybackHistory;
import com.github.curiousoddman.curious_tunes.dbobj.tables.Track;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.ALBUM</code>.
     */
    public final Album ALBUM = Album.ALBUM;

    /**
     * The table <code>public.ARTIST</code>.
     */
    public final Artist ARTIST = Artist.ARTIST;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.PENDING_ACTIONS</code>.
     */
    public final PendingActions PENDING_ACTIONS = PendingActions.PENDING_ACTIONS;

    /**
     * The table <code>public.PLAYBACK_HISTORY</code>.
     */
    public final PlaybackHistory PLAYBACK_HISTORY = PlaybackHistory.PLAYBACK_HISTORY;

    /**
     * The table <code>public.TRACK</code>.
     */
    public final Track TRACK = Track.TRACK;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Album.ALBUM,
            Artist.ARTIST,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            PendingActions.PENDING_ACTIONS,
            PlaybackHistory.PLAYBACK_HISTORY,
            Track.TRACK
        );
    }
}
