/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_tunes.dbobj;


import com.github.curiousoddman.curious_tunes.dbobj.tables.Album;
import com.github.curiousoddman.curious_tunes.dbobj.tables.Artist;
import com.github.curiousoddman.curious_tunes.dbobj.tables.FlywaySchemaHistory;
import com.github.curiousoddman.curious_tunes.dbobj.tables.PendingAction;
import com.github.curiousoddman.curious_tunes.dbobj.tables.PlaybackHistory;
import com.github.curiousoddman.curious_tunes.dbobj.tables.Track;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in public.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.ALBUM</code>.
     */
    public static final Album ALBUM = Album.ALBUM;

    /**
     * The table <code>public.ARTIST</code>.
     */
    public static final Artist ARTIST = Artist.ARTIST;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.PENDING_ACTION</code>.
     */
    public static final PendingAction PENDING_ACTION = PendingAction.PENDING_ACTION;

    /**
     * The table <code>public.PLAYBACK_HISTORY</code>.
     */
    public static final PlaybackHistory PLAYBACK_HISTORY = PlaybackHistory.PLAYBACK_HISTORY;

    /**
     * The table <code>public.TRACK</code>.
     */
    public static final Track TRACK = Track.TRACK;
}
