/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_tunes.dbobj.tables.records;


import com.github.curiousoddman.curious_tunes.dbobj.tables.PendingActions;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PendingActionsRecord extends UpdatableRecordImpl<PendingActionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.PENDING_ACTIONS.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.PENDING_ACTIONS.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.PENDING_ACTIONS.CLASSNAME</code>.
     */
    public void setClassname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.PENDING_ACTIONS.CLASSNAME</code>.
     */
    public String getClassname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.PENDING_ACTIONS.DATA</code>.
     */
    public void setData(byte[] value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.PENDING_ACTIONS.DATA</code>.
     */
    public byte[] getData() {
        return (byte[]) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PendingActionsRecord
     */
    public PendingActionsRecord() {
        super(PendingActions.PENDING_ACTIONS);
    }

    /**
     * Create a detached, initialised PendingActionsRecord
     */
    public PendingActionsRecord(Integer id, String classname, byte[] data) {
        super(PendingActions.PENDING_ACTIONS);

        setId(id);
        setClassname(classname);
        setData(data);
        resetChangedOnNotNull();
    }
}
