/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_tunes.dbobj.tables.records;


import com.github.curiousoddman.curious_tunes.dbobj.tables.TrackOverridesHistory;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TrackOverridesHistoryRecord extends UpdatableRecordImpl<TrackOverridesHistoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.TRACK_OVERRIDES_HISTORY.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.TRACK_OVERRIDES_HISTORY.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.TRACK_OVERRIDES_HISTORY.TRACK_ID</code>.
     */
    public void setTrackId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.TRACK_OVERRIDES_HISTORY.TRACK_ID</code>.
     */
    public Integer getTrackId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.TRACK_OVERRIDES_HISTORY.FIELD</code>.
     */
    public void setField(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.TRACK_OVERRIDES_HISTORY.FIELD</code>.
     */
    public String getField() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.TRACK_OVERRIDES_HISTORY.OLD_VALUE</code>.
     */
    public void setOldValue(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.TRACK_OVERRIDES_HISTORY.OLD_VALUE</code>.
     */
    public String getOldValue() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.TRACK_OVERRIDES_HISTORY.MODIFIED_AT</code>.
     */
    public void setModifiedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.TRACK_OVERRIDES_HISTORY.MODIFIED_AT</code>.
     */
    public LocalDateTime getModifiedAt() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TrackOverridesHistoryRecord
     */
    public TrackOverridesHistoryRecord() {
        super(TrackOverridesHistory.TRACK_OVERRIDES_HISTORY);
    }

    /**
     * Create a detached, initialised TrackOverridesHistoryRecord
     */
    public TrackOverridesHistoryRecord(Integer id, Integer trackId, String field, String oldValue, LocalDateTime modifiedAt) {
        super(TrackOverridesHistory.TRACK_OVERRIDES_HISTORY);

        setId(id);
        setTrackId(trackId);
        setField(field);
        setOldValue(oldValue);
        setModifiedAt(modifiedAt);
        resetChangedOnNotNull();
    }
}
