/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_tunes.dbobj.tables.records;


import com.github.curiousoddman.curious_tunes.dbobj.tables.Album;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AlbumRecord extends UpdatableRecordImpl<AlbumRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.ALBUM.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.ALBUM.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.ALBUM.FK_ARTIST</code>.
     */
    public void setFkArtist(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.ALBUM.FK_ARTIST</code>.
     */
    public Integer getFkArtist() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.ALBUM.NAME</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.ALBUM.NAME</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.ALBUM.IMAGE</code>.
     */
    public void setImage(byte[] value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.ALBUM.IMAGE</code>.
     */
    public byte[] getImage() {
        return (byte[]) get(3);
    }

    /**
     * Setter for <code>public.ALBUM.IMAGE_TYPE</code>.
     */
    public void setImageType(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.ALBUM.IMAGE_TYPE</code>.
     */
    public Byte getImageType() {
        return (Byte) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AlbumRecord
     */
    public AlbumRecord() {
        super(Album.ALBUM);
    }

    /**
     * Create a detached, initialised AlbumRecord
     */
    public AlbumRecord(Integer id, Integer fkArtist, String name, byte[] image, Byte imageType) {
        super(Album.ALBUM);

        setId(id);
        setFkArtist(fkArtist);
        setName(name);
        setImage(image);
        setImageType(imageType);
        resetChangedOnNotNull();
    }
}
