/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_tunes.dbobj.tables.records;


import com.github.curiousoddman.curious_tunes.dbobj.tables.Artist;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.20.10",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ArtistRecord extends UpdatableRecordImpl<ArtistRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.ARTIST.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.ARTIST.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.ARTIST.NAME</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.ARTIST.NAME</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.ARTIST.ICON</code>.
     */
    public void setIcon(byte[] value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.ARTIST.ICON</code>.
     */
    public byte[] getIcon() {
        return (byte[]) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ArtistRecord
     */
    public ArtistRecord() {
        super(Artist.ARTIST);
    }

    /**
     * Create a detached, initialised ArtistRecord
     */
    public ArtistRecord(Integer id, String name, byte[] icon) {
        super(Artist.ARTIST);

        setId(id);
        setName(name);
        setIcon(icon);
        resetTouchedOnNotNull();
    }
}
