/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_tunes.dbobj.tables.records;


import com.github.curiousoddman.curious_tunes.dbobj.tables.PlaybackHistory;

import java.time.OffsetDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PlaybackHistoryRecord extends UpdatableRecordImpl<PlaybackHistoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.PLAYBACK_HISTORY.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.PLAYBACK_HISTORY.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.PLAYBACK_HISTORY.DATETIME</code>.
     */
    public void setDatetime(OffsetDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.PLAYBACK_HISTORY.DATETIME</code>.
     */
    public OffsetDateTime getDatetime() {
        return (OffsetDateTime) get(1);
    }

    /**
     * Setter for <code>public.PLAYBACK_HISTORY.FK_TRACK</code>.
     */
    public void setFkTrack(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.PLAYBACK_HISTORY.FK_TRACK</code>.
     */
    public Integer getFkTrack() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PlaybackHistoryRecord
     */
    public PlaybackHistoryRecord() {
        super(PlaybackHistory.PLAYBACK_HISTORY);
    }

    /**
     * Create a detached, initialised PlaybackHistoryRecord
     */
    public PlaybackHistoryRecord(Integer id, OffsetDateTime datetime, Integer fkTrack) {
        super(PlaybackHistory.PLAYBACK_HISTORY);

        setId(id);
        setDatetime(datetime);
        setFkTrack(fkTrack);
        resetChangedOnNotNull();
    }
}
