/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_tunes.dbobj.tables.records;


import com.github.curiousoddman.curious_tunes.dbobj.tables.Track;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TrackRecord extends UpdatableRecordImpl<TrackRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.TRACK.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.TRACK.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.TRACK.FK_ALBUM</code>.
     */
    public void setFkAlbum(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.TRACK.FK_ALBUM</code>.
     */
    public Integer getFkAlbum() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.TRACK.TITLE</code>.
     */
    public void setTitle(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.TRACK.TITLE</code>.
     */
    public String getTitle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.TRACK.TRACK_NUMBER</code>.
     */
    public void setTrackNumber(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.TRACK.TRACK_NUMBER</code>.
     */
    public Integer getTrackNumber() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.TRACK.RELEASE_DATE</code>.
     */
    public void setReleaseDate(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.TRACK.RELEASE_DATE</code>.
     */
    public String getReleaseDate() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.TRACK.DISK_NUMBER</code>.
     */
    public void setDiskNumber(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.TRACK.DISK_NUMBER</code>.
     */
    public Integer getDiskNumber() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.TRACK.CREATOR</code>.
     */
    public void setCreator(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.TRACK.CREATOR</code>.
     */
    public String getCreator() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.TRACK.AUDIO_SAMPLE_RATE</code>.
     */
    public void setAudioSampleRate(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.TRACK.AUDIO_SAMPLE_RATE</code>.
     */
    public Integer getAudioSampleRate() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.TRACK.GENRE</code>.
     */
    public void setGenre(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.TRACK.GENRE</code>.
     */
    public String getGenre() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.TRACK.COMPOSER</code>.
     */
    public void setComposer(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.TRACK.COMPOSER</code>.
     */
    public String getComposer() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.TRACK.FILE_LOCATION</code>.
     */
    public void setFileLocation(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.TRACK.FILE_LOCATION</code>.
     */
    public String getFileLocation() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.TRACK.DURATION</code>.
     */
    public void setDuration(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.TRACK.DURATION</code>.
     */
    public Long getDuration() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>public.TRACK.STATUS</code>.
     */
    public void setStatus(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.TRACK.STATUS</code>.
     */
    public String getStatus() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.TRACK.LYRICS</code>.
     */
    public void setLyrics(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.TRACK.LYRICS</code>.
     */
    public String getLyrics() {
        return (String) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TrackRecord
     */
    public TrackRecord() {
        super(Track.TRACK);
    }

    /**
     * Create a detached, initialised TrackRecord
     */
    public TrackRecord(Integer id, Integer fkAlbum, String title, Integer trackNumber, String releaseDate, Integer diskNumber, String creator, Integer audioSampleRate, String genre, String composer, String fileLocation, Long duration, String status, String lyrics) {
        super(Track.TRACK);

        setId(id);
        setFkAlbum(fkAlbum);
        setTitle(title);
        setTrackNumber(trackNumber);
        setReleaseDate(releaseDate);
        setDiskNumber(diskNumber);
        setCreator(creator);
        setAudioSampleRate(audioSampleRate);
        setGenre(genre);
        setComposer(composer);
        setFileLocation(fileLocation);
        setDuration(duration);
        setStatus(status);
        setLyrics(lyrics);
        resetChangedOnNotNull();
    }
}
