/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_tunes.dbobj.tables;


import com.github.curiousoddman.curious_tunes.dbobj.Keys;
import com.github.curiousoddman.curious_tunes.dbobj.Public;
import com.github.curiousoddman.curious_tunes.dbobj.tables.records.PendingActionsRecord;

import java.util.Collection;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PendingActions extends TableImpl<PendingActionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.PENDING_ACTIONS</code>
     */
    public static final PendingActions PENDING_ACTIONS = new PendingActions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PendingActionsRecord> getRecordType() {
        return PendingActionsRecord.class;
    }

    /**
     * The column <code>public.PENDING_ACTIONS.ID</code>.
     */
    public final TableField<PendingActionsRecord, Integer> ID = createField(DSL.name("ID"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.PENDING_ACTIONS.CLASSNAME</code>.
     */
    public final TableField<PendingActionsRecord, String> CLASSNAME = createField(DSL.name("CLASSNAME"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.PENDING_ACTIONS.DATA</code>.
     */
    public final TableField<PendingActionsRecord, byte[]> DATA = createField(DSL.name("DATA"), SQLDataType.VARBINARY, this, "");

    private PendingActions(Name alias, Table<PendingActionsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PendingActions(Name alias, Table<PendingActionsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.PENDING_ACTIONS</code> table reference
     */
    public PendingActions(String alias) {
        this(DSL.name(alias), PENDING_ACTIONS);
    }

    /**
     * Create an aliased <code>public.PENDING_ACTIONS</code> table reference
     */
    public PendingActions(Name alias) {
        this(alias, PENDING_ACTIONS);
    }

    /**
     * Create a <code>public.PENDING_ACTIONS</code> table reference
     */
    public PendingActions() {
        this(DSL.name("PENDING_ACTIONS"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<PendingActionsRecord, Integer> getIdentity() {
        return (Identity<PendingActionsRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<PendingActionsRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_2;
    }

    @Override
    public PendingActions as(String alias) {
        return new PendingActions(DSL.name(alias), this);
    }

    @Override
    public PendingActions as(Name alias) {
        return new PendingActions(alias, this);
    }

    @Override
    public PendingActions as(Table<?> alias) {
        return new PendingActions(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PendingActions rename(String name) {
        return new PendingActions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PendingActions rename(Name name) {
        return new PendingActions(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PendingActions rename(Table<?> name) {
        return new PendingActions(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PendingActions where(Condition condition) {
        return new PendingActions(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PendingActions where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PendingActions where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PendingActions where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PendingActions where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PendingActions where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PendingActions where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PendingActions where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PendingActions whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PendingActions whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
