/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_tunes.dbobj.tables;


import com.github.curiousoddman.curious_tunes.dbobj.Indexes;
import com.github.curiousoddman.curious_tunes.dbobj.Keys;
import com.github.curiousoddman.curious_tunes.dbobj.Public;
import com.github.curiousoddman.curious_tunes.dbobj.tables.Track.TrackPath;
import com.github.curiousoddman.curious_tunes.dbobj.tables.records.TrackOverridesHistoryRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TrackOverridesHistory extends TableImpl<TrackOverridesHistoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.TRACK_OVERRIDES_HISTORY</code>
     */
    public static final TrackOverridesHistory TRACK_OVERRIDES_HISTORY = new TrackOverridesHistory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TrackOverridesHistoryRecord> getRecordType() {
        return TrackOverridesHistoryRecord.class;
    }

    /**
     * The column <code>public.TRACK_OVERRIDES_HISTORY.ID</code>.
     */
    public final TableField<TrackOverridesHistoryRecord, Integer> ID = createField(DSL.name("ID"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.TRACK_OVERRIDES_HISTORY.TRACK_ID</code>.
     */
    public final TableField<TrackOverridesHistoryRecord, Integer> TRACK_ID = createField(DSL.name("TRACK_ID"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.TRACK_OVERRIDES_HISTORY.FIELD</code>.
     */
    public final TableField<TrackOverridesHistoryRecord, String> FIELD = createField(DSL.name("FIELD"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.TRACK_OVERRIDES_HISTORY.OLD_VALUE</code>.
     */
    public final TableField<TrackOverridesHistoryRecord, String> OLD_VALUE = createField(DSL.name("OLD_VALUE"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.TRACK_OVERRIDES_HISTORY.MODIFIED_AT</code>.
     */
    public final TableField<TrackOverridesHistoryRecord, LocalDateTime> MODIFIED_AT = createField(DSL.name("MODIFIED_AT"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private TrackOverridesHistory(Name alias, Table<TrackOverridesHistoryRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TrackOverridesHistory(Name alias, Table<TrackOverridesHistoryRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.TRACK_OVERRIDES_HISTORY</code> table
     * reference
     */
    public TrackOverridesHistory(String alias) {
        this(DSL.name(alias), TRACK_OVERRIDES_HISTORY);
    }

    /**
     * Create an aliased <code>public.TRACK_OVERRIDES_HISTORY</code> table
     * reference
     */
    public TrackOverridesHistory(Name alias) {
        this(alias, TRACK_OVERRIDES_HISTORY);
    }

    /**
     * Create a <code>public.TRACK_OVERRIDES_HISTORY</code> table reference
     */
    public TrackOverridesHistory() {
        this(DSL.name("TRACK_OVERRIDES_HISTORY"), null);
    }

    public <O extends Record> TrackOverridesHistory(Table<O> path, ForeignKey<O, TrackOverridesHistoryRecord> childPath, InverseForeignKey<O, TrackOverridesHistoryRecord> parentPath) {
        super(path, childPath, parentPath, TRACK_OVERRIDES_HISTORY);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org",
            "jOOQ version:3.19.28",
            "schema version:none"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class TrackOverridesHistoryPath extends TrackOverridesHistory implements Path<TrackOverridesHistoryRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TrackOverridesHistoryPath(Table<O> path, ForeignKey<O, TrackOverridesHistoryRecord> childPath, InverseForeignKey<O, TrackOverridesHistoryRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private TrackOverridesHistoryPath(Name alias, Table<TrackOverridesHistoryRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TrackOverridesHistoryPath as(String alias) {
            return new TrackOverridesHistoryPath(DSL.name(alias), this);
        }

        @Override
        public TrackOverridesHistoryPath as(Name alias) {
            return new TrackOverridesHistoryPath(alias, this);
        }

        @Override
        public TrackOverridesHistoryPath as(Table<?> alias) {
            return new TrackOverridesHistoryPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_OVERRIDES_TRACK_ID);
    }

    @Override
    public Identity<TrackOverridesHistoryRecord, Integer> getIdentity() {
        return (Identity<TrackOverridesHistoryRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<TrackOverridesHistoryRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_A;
    }

    @Override
    public List<ForeignKey<TrackOverridesHistoryRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_AD);
    }

    private transient TrackPath _track;

    /**
     * Get the implicit join path to the <code>public.TRACK</code> table.
     */
    public TrackPath track() {
        if (_track == null)
            _track = new TrackPath(this, Keys.CONSTRAINT_AD, null);

        return _track;
    }

    @Override
    public TrackOverridesHistory as(String alias) {
        return new TrackOverridesHistory(DSL.name(alias), this);
    }

    @Override
    public TrackOverridesHistory as(Name alias) {
        return new TrackOverridesHistory(alias, this);
    }

    @Override
    public TrackOverridesHistory as(Table<?> alias) {
        return new TrackOverridesHistory(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TrackOverridesHistory rename(String name) {
        return new TrackOverridesHistory(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TrackOverridesHistory rename(Name name) {
        return new TrackOverridesHistory(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TrackOverridesHistory rename(Table<?> name) {
        return new TrackOverridesHistory(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TrackOverridesHistory where(Condition condition) {
        return new TrackOverridesHistory(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TrackOverridesHistory where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TrackOverridesHistory where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TrackOverridesHistory where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TrackOverridesHistory where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TrackOverridesHistory where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TrackOverridesHistory where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TrackOverridesHistory where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TrackOverridesHistory whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TrackOverridesHistory whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
